import type { DashboardCardId } from '@varaperformance/core';

export const CARD_DISPLAY_NAMES: Record<DashboardCardId, string> = {
  'motivation-quote': 'Motivation Quote',
  'goal-workouts': 'Workouts Goal',
  'goal-calories': 'Calories Goal',
  'goal-protein': 'Protein Goal',
  'goal-carbs': 'Carbs Goal',
  'goal-fats': 'Fats Goal',
  'goal-water': 'Water Goal',
  'stat-streak': 'Current Streak',
  'stat-yearly': 'This Year',
  'stat-calories': 'Calories Burned',
  'stat-prs': 'Personal Records',
  'training-overview': 'Training Overview',
  'body-composition': 'Body Composition',
  'weight-progress': 'Weight Progress',
  'strength-progress': 'Strength Progress',
  'weekly-duration': 'Weekly Duration',
  'todays-macros': "Today's Macros",
  'heart-rate': 'Heart Rate Zones',
  'sleep-recovery': 'Sleep & Recovery',
  'weekly-volume': 'Weekly Volume',
  'meal-plan': 'Meal Plan',
  'body-measurements': 'Body Measurements',
  'lifestyle-adherence': 'Lifestyle Adherence',
  'stack-compliance': 'Stack Compliance',
  'hydration-trend': 'Hydration Trend',
  'nutrition-trend': 'Nutrition Trend',
  'pr-timeline': 'PR Timeline',
  'goal-steps': 'Steps Goal',
  'goal-sleep': 'Sleep Goal',
  'step-trend': 'Step Trend',
  habits: 'Habits',
  achievements: 'Achievements',
  challenges: 'Challenges',
  'recent-workouts': 'Recent Workouts',
};
